modLoader = "javafml"
loaderVersion = "[28,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/RealHeart/ZMusic/issues"
[[mods]]
modId = "zmusic"
version = "${version}"
displayName = "ZMusic Mod"
description = "Powerful Music System"
displayURL = "https://m.zplu.cc"
authors = "ZhenXin"
[[dependencies.zmusic]]
modId = "forge"
mandatory = true
versionRange = "[28,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.zmusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.14.4,1.15)"
ordering = "NONE"
side = "CLIENT"